version: '3.3'
services:
  firefly:
    container_name: firefly
    hostname: firefly
    restart: always
    networks:
        - fireflynet
    image: jc5x/firefly-iii:latest
    volumes:
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
    env_file: .env
    ports:
      - 127.0.0.1:80:8080
    depends_on:
      - fireflydb
  fireflydb:
    image: yobasystems/alpine-mariadb:latest
    container_name: fireflydb
    hostname: fireflydb
    restart: always
    expose:
        - "3306"
    networks:
        - fireflynet
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
volumes:
   firefly_iii_export:
   firefly_iii_upload:
   firefly_iii_db:
networks:
    fireflynet:
